version: '2.1'
services:
  sql-client:
    user: flink:flink
    build: .
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    volumes:
      - ./data:/tmp/iceberg
  jobmanager:
    user: flink:flink
    build: .
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./data:/tmp/iceberg
  taskmanager:
    user: flink:flink
    build: .
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ./data:/tmp/iceberg
  postgres:
    image: postgres:15.2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: demo
    volumes:
      - ./demo-small.sql:/docker-entrypoint-initdb.d/demo.sql
volumes:
  shared-tmpfs:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"